version: 1
build:
  binary: tfabd
accounts:
- name: main
  coins:
  - 10000000000000000tfab
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: tfab
    evm:
      params:
        evm_denom: tfab
    gov:
      deposit_params:
        min_deposit:
        - amount: "1000000"
          denom: tfab
    mint:
      params:
        mint_denom: tfab
    staking:
      params:
        bond_denom: tfab
  chain_id: tokenfab-testnet
validators:
- name: main
  bonded: 100000000000tfab
  home: $HOME/.tfabd